version: '3'
services:
  server:
    container_name: template_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/template?schema=public
      JWT_KEY:
      JWT_EXPIRATION: 24h
      APP_PORT: 3000
      BCRYPT_SALT_ROUNDS: 10
      LOG_LEVEL: debug
      LOG_DIR: logs
      NODE_ENV: development

  db:
    container_name: temlpate_db
    image: postgres:15
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: template
    volumes:
      - pg_data:/var/lib/postgresql
volumes:
  pg_data: {}